apiVersion: v1
kind: PersistentVolume
metadata:
 name: pervol
spec:
 storageClassName: store
 capacity:
  storage: 500Mi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/home/poseidon/Downloads/Project/files/"
 
