apiVersion: v1
kind: Service                    
metadata:
 name: webservice 
spec:
 type: LoadBalancer
 selector:
  app: website
 ports:
 - port: 8080
   targetPort: 80
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: webdeployment
spec:
 selector:
  matchLabels:
   app: website
 template:
  metadata:
   labels:
    app: website
  spec:
   containers:
   - name: web
     image: wordpress:6.2.1-apache
     ports:
      - containerPort: 80
     env:
      - name: WORDPRESS_DB_HOST
        value: mysql
      - name: WORDPRESS_DB_USER
        value: admin
      - name: WORDPRESS_DB_PASSWORD
        value: password
      - name: WORDPRESS_DB_NAME
        value: mysql
     volumeMounts:
     - name: wpclaim
       mountPath: /var/www/html   
        
   volumes: 
   - name: wpclaim    
     persistentVolumeClaim:
      claimName: wpclaim
