apiVersion: v1
kind: PersistentVolume
metadata:
 name: wpvolume
spec:
 storageClassName: volume
 capacity:
  storage: 500Mi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/home/poseidon/Downloads/Project/wp/"
